# Python
nome=input('Qual o seu nome?')
idade=input('Qual a sua idade?')
peso=input('Qual o seu peso?')
print('Nome:',nome)
print('Idade: ',idade)
print('Peso: ',peso,'Kg')
print('Resumindo, você é ',nome,' Tem ',idade,' anos e pesa ',peso,'Kg')
calc=input('quanto é 2+2?')
print(calc)